/* Shared headshot resolution for the offline builders.
 *
 * WHY THIS EXISTS
 *
 * nba-headshots ships 1,785 face crops, but its players/metadata/players.json
 * describes only 572 of them — the active roster the pipeline last refreshed.
 * Every builder here trusted that file, so Kareem, Jordan, Kobe, Karl Malone
 * and Tim Duncan all had a committed PNG sitting in the repo and still drew a
 * blank silhouette. Headshot coverage on the bar chart races read 5%.
 *
 * So the file listing is the source of truth for WHICH faces exist, and
 * nba-player-data's player-headshots.json is the only thing that maps a NAME to
 * one of those files.
 *
 * THE TRAP IN THAT MAP
 *
 * It resolves some fathers to their sons' photos:
 *
 *     "Larry Nance"      -> 1626204-larry-nance-jr
 *     "Tim Hardaway"     -> 203501-tim-hardaway-jr
 *     "Jaren Jackson"    -> 1628991-jaren-jackson-jr
 *     "Dee Brown (1968)" -> 200793-dee-brown
 *
 * Using it raw puts the wrong man's face on a card. The guard: a mapped file is
 * accepted only when the slug in the filename matches the slugified player
 * name exactly. That rejects all four cases above.
 *
 * It also rejects ~60 harmless ones where the map simply drops a "Jr." that has
 * no elder counterpart (Danuel House, Dennis Smith, Charlie Brown). Those lose
 * a face they could have had. That is the intended trade: an initials disc is a
 * blemish, the wrong player's face is a lie.
 *
 * players.json stays in the mix as a trusted overlay — it is generated by the
 * pipeline itself, has no collisions, and agrees with every slug-checked entry.
 */

import fs from "fs";
import path from "path";
import zlib from "zlib";

/* ---------------- alpha bounding box ----------------
 *
 * The face crops are cut-outs: RGBA, background removed, and the head occupies
 * only about 46% of the 256px width and 58% of the height. Drawing the whole
 * canvas makes the head tiny; clipping it to a circle to compensate cuts off
 * ears, chin and hair. Neither is acceptable.
 *
 * So the real extent of the head is measured here, at build time, and shipped
 * with the race as a normalized [x, y, w, h] source rectangle. The player draws
 * exactly that region, whole, scaled to fit — nothing cropped, nothing tiny.
 *
 * Done with Node's own zlib rather than an image library on purpose: these
 * builders are run with a bare `node tools/build_races.mjs`, and adding a
 * dependency would mean an npm install before every build.
 *
 * Handles 8-bit non-interlaced truecolour-with-alpha (colour type 6), which is
 * what every file in nba-headshots is. Anything else returns null and the
 * caller falls back to the full canvas.
 */
/* Exported because the Teammates cards need the same measurement for a
 * different shape: the races draw a landscape tile, that card draws a circle,
 * and both have to know where the head actually is inside a cut-out rather
 * than guessing from a fixed fraction of the canvas. */
export function alphaBox(file, y0Frac, y1Frac) {
  let buf;
  try { buf = fs.readFileSync(file); } catch (e) { return null; }
  if (buf.length < 8 || buf.readUInt32BE(0) !== 0x89504e47) return null;

  let w = 0, h = 0, depth = 0, colour = 0, interlace = 0;
  const idat = [];
  let off = 8;
  while (off + 8 <= buf.length) {
    const len = buf.readUInt32BE(off);
    const type = buf.toString("ascii", off + 4, off + 8);
    const data = buf.subarray(off + 8, off + 8 + len);
    if (type === "IHDR") {
      w = data.readUInt32BE(0); h = data.readUInt32BE(4);
      depth = data[8]; colour = data[9]; interlace = data[12];
    } else if (type === "IDAT") {
      idat.push(data);
    } else if (type === "IEND") break;
    off += 12 + len;
  }
  if (depth !== 8 || colour !== 6 || interlace !== 0 || !w || !h) return null;

  let raw;
  try { raw = zlib.inflateSync(Buffer.concat(idat)); } catch (e) { return null; }

  const bpp = 4, stride = w * bpp;
  if (raw.length < (stride + 1) * h) return null;

  // Un-filter in place. Each scanline is one filter byte then `stride` bytes.
  const cur = Buffer.alloc(stride);
  const prev = Buffer.alloc(stride);
  let minX = w, minY = h, maxX = -1, maxY = -1;
  const ALPHA_MIN = 16;   // ignore the soft feathered edge the cut-out leaves
  /* Optional vertical band, as fractions of the image height. Measuring the
   * whole cut-out gives the SUBJECT — head and shoulders — whose centre is the
   * chest, not the face. Measuring just the top of it gives the head, which is
   * what a circular avatar has to be centred on. */
  const bandTop = y0Frac == null ? 0 : Math.max(0, Math.floor(y0Frac * h));
  const bandBottom = y1Frac == null ? h : Math.min(h, Math.ceil(y1Frac * h));

  for (let y = 0; y < h; y++) {
    const base = y * (stride + 1);
    const filter = raw[base];
    raw.copy(cur, 0, base + 1, base + 1 + stride);
    for (let i = 0; i < stride; i++) {
      const a = i >= bpp ? cur[i - bpp] : 0;   // left
      const b = prev[i];                       // up
      const c = i >= bpp ? prev[i - bpp] : 0;  // up-left
      let v = cur[i];
      if (filter === 1) v += a;
      else if (filter === 2) v += b;
      else if (filter === 3) v += (a + b) >> 1;
      else if (filter === 4) {
        const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
        v += (pa <= pb && pa <= pc) ? a : (pb <= pc ? b : c);
      }
      cur[i] = v & 0xff;
    }
    for (let x = 0; y >= bandTop && y < bandBottom && x < w; x++) {
      if (cur[x * bpp + 3] >= ALPHA_MIN) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
    cur.copy(prev);
  }
  if (maxX < 0) return null;
  const r = n => Math.round(n * 1000) / 1000;
  return [r(minX / w), r(minY / h), r((maxX - minX + 1) / w), r((maxY - minY + 1) / h)];
}

export const HEADSHOT_BASE =
  "https://jsierrahoopshype.github.io/nba-headshots/players/headshots/face/";
export const SILHOUETTE =
  "https://jsierrahoopshype.github.io/nba-headshots/fallbacks/player_silhouette.svg";

function slugify(name) {
  return String(name)
    .toLowerCase()
    .replace(/['.&]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/* Accepts either the repo root or the players/metadata directory, so existing
 * command lines keep working. Returns the directory holding the face crops, or
 * null when it cannot be found. */
function findFaceDir(hsPath) {
  const candidates = [
    path.join(hsPath, "players", "headshots", "face"),           // repo root
    path.join(hsPath, "..", "headshots", "face"),                 // players/metadata
    path.join(hsPath, "headshots", "face"),                       // players/
    path.join(hsPath, "face")
  ];
  for (const c of candidates) {
    try { if (fs.statSync(c).isDirectory()) return c; } catch (e) { /* next */ }
  }
  return null;
}

/**
 * @param {string} hsPath  nba-headshots repo root or its players/metadata dir
 * @param {object} headMap nba-player-data/player-headshots.json (name -> slug)
 * @returns {{ urlFor:(name:string)=>string|null, faceOf:(name:string)=>string,
 *             size:number, stats:object }}
 */
export function buildFaceIndex(hsPath, headMap) {
  const stats = { onDisk: 0, fromMetadata: 0, fromMap: 0, rejected: 0, rejects: [] };

  const faceDir = findFaceDir(hsPath);
  const onDisk = new Set();
  if (faceDir) {
    for (const f of fs.readdirSync(faceDir)) {
      if (/\.png$/i.test(f)) onDisk.add(f.replace(/\.png$/i, ""));
    }
  }
  stats.onDisk = onDisk.size;

  const byName = new Map();

  // 1. the pipeline's own metadata, where it exists
  let meta = null;
  for (const p of [path.join(hsPath, "players.json"),
                   path.join(hsPath, "players", "metadata", "players.json")]) {
    try { meta = JSON.parse(fs.readFileSync(p, "utf8")); break; } catch (e) { /* next */ }
  }
  for (const p of ((meta && meta.players) || [])) {
    const h = p.headshot;
    if (!h || !h.face || !h.filename) continue;
    const slug = h.filename.replace(/\.png$/i, "");
    if (onDisk.size && !onDisk.has(slug)) continue;   // metadata ahead of the files
    byName.set(p.full_name, slug);
    stats.fromMetadata++;
  }

  // 2. the name map, gated on the file existing AND the slug matching the name
  if (onDisk.size) {
    for (const [name, slug] of Object.entries(headMap || {})) {
      if (!slug || byName.has(name) || !onDisk.has(slug)) continue;
      const tail = slug.indexOf("-") >= 0 ? slug.slice(slug.indexOf("-") + 1) : "";
      if (tail === slugify(name)) {
        byName.set(name, slug);
        stats.fromMap++;
      } else {
        stats.rejected++;
        if (stats.rejects.length < 6) stats.rejects.push(`${name} -> ${slug}`);
      }
    }
  }

  // Cached because several races share the same players and each box costs a
  // full PNG inflate.
  const boxCache = new Map();
  function boxFor(name) {
    if (!faceDir || !byName.has(name)) return null;
    const slug = byName.get(name);
    if (!boxCache.has(slug)) boxCache.set(slug, alphaBox(path.join(faceDir, slug + ".png")));
    return boxCache.get(slug);
  }

  return {
    size: byName.size,
    stats,
    urlFor: name => (byName.has(name) ? HEADSHOT_BASE + byName.get(name) + ".png" : null),
    faceOf: name => (byName.has(name) ? HEADSHOT_BASE + byName.get(name) + ".png" : SILHOUETTE),
    /* Normalized [x, y, w, h] of the head inside its 256x256 canvas, so a
     * renderer can draw the whole head at a sensible size. null = draw it all. */
    boxFor
  };
}

export function reportFaceIndex(idx, label) {
  const s = idx.stats;
  if (!s.onDisk) {
    console.log(`${label}: ${idx.size} faces from metadata only — the face directory was ` +
      `not found next to the path given, so coverage is limited to the active roster. ` +
      `Pass the nba-headshots repo root to use all of them.`);
    return;
  }
  console.log(`${label}: ${idx.size} names resolved to a face ` +
    `(${s.fromMetadata} from players.json, ${s.fromMap} more from the verified name map; ` +
    `${s.onDisk} PNGs on disk, ${s.rejected} mappings rejected as name/slug mismatches).`);
  if (s.rejects.length) console.log(`  rejected e.g. ${s.rejects.join(", ")}`);
}

/* ==================================================================
 * bar-chart-race/assets/headshots — the wide source
 * ==================================================================
 *
 * nba-headshots resolves 572 names. bar-chart-race ships 6,769 PNGs keyed by
 * full name, and on the pool players the two sources are not complementary:
 * every nba-headshots face that a pool needs is also in bar-chart-race, and
 * bar-chart-race has 306 more on top. So for anything that wants "only players
 * with a real photo", this is the index to ask.
 *
 * Three things make the difference between 60% coverage and 38%:
 *
 *   Case. The file is "Kevin Mchale.png", "Fred Vanvleet.png", "Zach Lavine.png".
 *   Matching case-sensitively lost McHale, VanVleet, LaVine, LaMelo Ball,
 *   LaMarcus Aldridge, DeAndre Jordan, DeMarcus Cousins and Tracy McGrady.
 *
 *   Diacritics. "Nikola Jokić.png" against "Nikola Jokic" in the stats files.
 *
 *   Punctuation. "Amar'e Stoudemire", "B.J. Armstrong". Punctuation is
 *   removed rather than spaced, so "Amar'e" and "Amare" agree and "B.J." and
 *   "BJ" agree without inventing a word boundary that is not there.
 *
 * THE TRAP, AGAIN
 *
 * Generational suffixes are the same hazard buildFaceIndex was written to dodge,
 * in a different costume. Only "Larry Nance Jr..png" exists — the father has no
 * photo — so a stem match on "larry nance" hands the elder Nance his son's face.
 * Across the pools there are eight names where the only file carrying their stem
 * has a suffix they do not:
 *
 *     Jimmy Butler <- III        Larry Nance <- Jr.        (wrong man)
 *     Marcus Morris <- Sr.       Glenn Robinson <- III     (wrong man)
 *     Kelly Oubre <- Jr.         Tim Hardaway <- Jr.       (wrong man)
 *                                Ron Harper <- Jr.         (wrong man)
 *                                John Lucas <- III         (wrong man)
 *
 * Five of the eight are a different player. So the rule is: a stem match is
 * refused whenever the FILE carries a generational suffix the name does not.
 * That costs Butler, Morris and Oubre a photo they could have had, and it is
 * the same trade buildFaceIndex makes above — an initials disc is a blemish,
 * the wrong player's face is a lie.
 *
 * Files of exactly the NBA CDN's grey placeholder size are not photographs and
 * are skipped, which is what makes "has a headshot" true rather than roughly
 * true: 3,307 of the 6,769 are that placeholder.
 *
 * _unmapped/ holds another 1,687 real crops keyed by NBA person id, reachable
 * through nba-player-data's player-headshots.json, whose values start with that
 * id. That map has the father/son collisions buildFaceIndex documents, so the
 * same slug check applies: "Tim Hardaway" -> "203501-tim-hardaway-jr" is
 * rejected, because the slug in the value is not the slug of the name asked for.
 */

const PLACEHOLDER_BYTES = 15000;   // below this it is the CDN's grey silhouette

const bcrFold = s => String(s).normalize("NFD").replace(/[̀-ͯ]/g, "");
const bcrNorm = s => bcrFold(s).toLowerCase()
  .replace(/[^a-z0-9 ]+/g, "").replace(/\s+/g, " ").trim();
const bcrStem = s => bcrNorm(s).replace(/\b(jr|sr|ii|iii|iv|v)\b/g, "")
  .replace(/\s+/g, " ").trim();

const bcrHasSuffix = s => /\b(jr|sr|ii|iii|iv|v)\b/.test(bcrNorm(s));

/**
 * @param {string} dir       bar-chart-race/assets/headshots
 * @param {object} [headMap] nba-player-data/player-headshots.json, for _unmapped
 * @returns {{ fileFor:(name:string)=>string|null, size:number, stats:object }}
 */
export function buildBcrIndex(dir, headMap) {
  const exact = new Map();          // normalized name -> file
  const stem = new Map();           // suffix-stripped stem -> file
  const stemCount = new Map();      // stem -> how many files reduce to it
  const stemSuffixed = new Map();   // stem -> does that one file carry a suffix
  const byId = new Map();           // NBA person id -> file
  const stats = { files: 0, placeholders: 0, unmapped: 0, suffixGuarded: 0 };

  let entries = [];
  try { entries = fs.readdirSync(dir); } catch (e) { return emptyBcrIndex(); }

  for (const f of entries) {
    if (!/\.png$/i.test(f)) continue;
    const full = path.join(dir, f);
    let size = 0;
    try { size = fs.statSync(full).size; } catch (e) { continue; }
    if (size < PLACEHOLDER_BYTES) { stats.placeholders++; continue; }
    stats.files++;
    const raw = f.replace(/\.png$/i, "");
    const e = bcrNorm(raw), s = bcrStem(raw);
    if (!exact.has(e)) exact.set(e, full);
    stemCount.set(s, (stemCount.get(s) || 0) + 1);
    if (!stem.has(s)) { stem.set(s, full); stemSuffixed.set(s, bcrHasSuffix(raw)); }
  }

  const unDir = path.join(dir, "_unmapped");
  try {
    for (const f of fs.readdirSync(unDir)) {
      if (!/\.png$/i.test(f)) continue;
      const full = path.join(unDir, f);
      if (fs.statSync(full).size < PLACEHOLDER_BYTES) continue;
      byId.set(f.replace(/\.png$/i, ""), full);
      stats.unmapped++;
    }
  } catch (e) { /* no _unmapped directory, fine */ }

  function fileFor(name) {
    const hit = exact.get(bcrNorm(name));
    if (hit) return hit;
    const s = bcrStem(name);
    if (stemCount.get(s) === 1) {
      if (stemSuffixed.get(s) && !bcrHasSuffix(name)) stats.suffixGuarded++;
      else return stem.get(s);
    }
    /* _unmapped, through the name map — with buildFaceIndex's slug check, since
     * this map points several fathers at their sons. */
    const mapped = headMap && headMap[name];
    if (mapped) {
      const str = String(mapped);
      const cut = str.indexOf("-");
      const id = cut < 0 ? str : str.slice(0, cut);
      const slug = cut < 0 ? "" : str.slice(cut + 1);
      if (slug === slugify(name) && byId.has(id)) return byId.get(id);
    }
    return null;
  }

  return { fileFor, size: exact.size, stats };
}

function emptyBcrIndex() {
  return { fileFor: () => null, size: 0, stats: { files: 0, placeholders: 0, unmapped: 0 } };
}

/* ---------------- square head tile ----------------
 *
 * Same framing the Teammates scoreboard uses, because the same thing is true
 * everywhere a face goes in a circle or a rounded square: these sources are
 * head-and-shoulders cut-outs, so their centre of mass is the chest. A square
 * around that leaves the face high and half out of frame; a square hung off the
 * crown cuts the chin off. Measure the head's width in the top third of the
 * cut-out, assume a head is ~1.4x as tall as it is wide, centre on the middle
 * of that, and make the square 2.25 head-widths across so the whole head still
 * fits once a circle takes the corners off.
 *
 * Square in, square out, one resize — never stretched on either axis.
 */
const HEAD_BAND = 0.34;
const HEAD_PAD = 2.25;
const HEAD_RATIO = 1.4;

/**
 * @param {string} src   source PNG (a background-removed cut-out)
 * @param {number} side  output edge in px
 * @param {object} png   { decodePng, crop, resize, encodePng } from ./png.mjs
 * @returns {Buffer|null}
 */
export function headTile(src, side, png) {
  const img = png.decodePng(src);
  if (!img) return null;
  const full = alphaBox(src);
  let s, x, y;
  if (full) {
    const fy = full[1] * img.h, fh = full[3];
    const headBox = alphaBox(src, full[1], full[1] + fh * HEAD_BAND) || full;
    const hx = headBox[0] * img.w, hw = headBox[2] * img.w;
    s = Math.round(Math.min(img.w, img.h, hw * HEAD_PAD));
    x = Math.round(hx + hw / 2 - s / 2);
    y = Math.round(fy + hw * HEAD_RATIO / 2 - s / 2);
  } else {
    s = Math.min(img.w, Math.round(img.h * 0.78));
    x = Math.round((img.w - s) / 2);
    y = 0;
  }
  x = Math.max(0, Math.min(x, img.w - s));
  y = Math.max(0, Math.min(y, img.h - s));
  return png.encodePng(png.resize(png.crop(img, x, y, s, s), side, side));
}

/* ---------------- accent-folded filename lookup ----------------
 *
 * Race data spells names in ASCII; the PNGs on disk keep their diacritics. So
 * a builder asking the filesystem for "Jusuf Nurkic.png" misses "Jusuf
 * Nurkić.png" sitting beside it, and the player silently loses his baked tile
 * to a remote URL. Nothing errors, which is why it survived a 99% run.
 *
 * Folding is done ONCE over a directory listing, not per lookup: one syscall
 * against thousands of name resolutions.
 *
 * This is deliberately fold-only and does NOT do what buildBcrIndex does. That
 * one also matches a suffix-stripped stem, which is how "Tim Hardaway" reaches
 * his son's photograph. Accents are a spelling difference for one man; a stem
 * match is a guess about which of two men is meant. Keeping them apart lets a
 * builder take the safe half without the risky one.
 */
export const foldAccents = s =>
  String(s).normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();

/**
 * @param {string} dir  a folder of .png headshots
 * @returns {Map<string,string>} folded filename stem -> absolute path
 */
export function foldedPngIndex(dir) {
  const idx = new Map();
  let entries = [];
  try { entries = fs.readdirSync(dir); } catch (e) { return idx; }
  /* SORTED, then first wins. Two files can fold to the same key - a folder
   * holding both "Jusuf Nurkic.png" and "Jusuf Nurkić.png" - and taking
   * whichever readdir happened to hand over first would make the build's
   * output depend on the filesystem's mood. Sorting also settles that tie the
   * useful way: plain ASCII sorts ahead of its accented twin, so the exact
   * spelling wins and the fold only ever fills a gap. */
  for (const f of entries.slice().sort()) {
    if (!/\.png$/i.test(f)) continue;
    const k = foldAccents(f.replace(/\.png$/i, ""));
    if (!idx.has(k)) idx.set(k, path.join(dir, f));
  }
  return idx;
}

/* ---------------- head-normalised race tile ----------------
 *
 * WHAT IS WRONG WITH THE FIXED-FRACTION TILE
 *
 * raceFaceTile takes the top 80% of whatever it is given and cover-crops that
 * to 1.4:1. That is correct arithmetic on an assumption that does not hold:
 * that every source frames its subject the same way. They do not. A contact
 * sheet of 752 tiles shows heads at wildly different sizes - some filling the
 * frame with the crown cut off, others small and low with dead space above -
 * because an official NBA portrait, an old scanned photo and a bbref crop
 * place the head in different parts of the picture. Each tile is fine alone.
 * Together they do not look like one set.
 *
 * A fixed fraction cannot fix that. Only finding the head can.
 *
 * WHY alphaBox AND NOT SOMETHING CLEVERER
 *
 * These portraits are cut-outs: the subject is opaque and the background is
 * transparent, so the alpha channel says exactly where the person is. That is
 * a fact in the file, not an inference from it. alphaBox already does this and
 * headTile already relies on it for the circular avatars on the Teammates
 * cards, so this is the same proven measurement applied to a shape that never
 * got it.
 *
 * The obvious alternative - find the face by looking for skin tones - is worse
 * on both counts. It guesses where alpha knows, and it degrades with skin
 * tone, which in a league that is majority Black players means it would fail
 * hardest on most of the set. Not a trade worth making when the answer is
 * sitting in the alpha channel.
 *
 * WHEN THERE IS NO ALPHA
 *
 * Old scans and JPEG-sourced images arrive opaque, and there is nothing to
 * measure. Those fall back to the existing fixed-fraction tile unchanged,
 * because a guessed crop is worse than a known-imperfect one. The caller is
 * told which happened so the split is visible rather than assumed.
 */

/* Fractions of the OUTPUT tile, chosen to sit near the middle of what the
 * current set already does rather than at some ideal: the median tile should
 * barely move, and only the outliers should travel. Tune by eye against
 * tools/build_face_compare.mjs, not by argument. */
const TILE_HEAD_HEIGHT = 0.72;   // head box height as a fraction of tile height
const TILE_HEAD_CENTRE = 0.46;   // where the head's centre sits down the tile

/**
 * A race tile cropped around the head rather than around the frame.
 *
 * FINDING THE NECK, NOT ASSUMING IT
 *
 * The first version of this took the head to be the top 34% of the cut-out and
 * measured its width there. That is the same mistake as the fixed 80% crop it
 * was meant to replace: a fraction standing in for a measurement. On a tight
 * portrait the band is all head; on a chest-up one it reaches the shoulders, so
 * "head width" became shoulder width and the head came out half the size. A
 * test with one tight and one wide cut-out caught it - 0.512 against 0.250 of
 * the tile - which no amount of staring at the code would have.
 *
 * So the head is found by where the SUBJECT GETS WIDER. Walking down from the
 * crown, opaque width holds roughly steady through the head and then jumps at
 * the shoulders. That jump is the neck, it is in the picture rather than in a
 * constant, and it does not care how the photographer framed the shot.
 *
 * @param {string} src   source PNG
 * @param {number} outW  tile width
 * @param {number} outH  tile height
 * @param {object} png   the png module (passed in, as headTile does, so this
 *                       file and png.mjs do not import each other)
 * @returns {{buf:Buffer, method:"head"}|null} null when there is no cut-out to
 *   measure, so the caller falls back to the existing crop.
 */
export function headRaceTile(src, outW, outH, png) {
  const img = png.decodePng(src);
  if (!img) return null;
  const { w, h, data } = img;

  /* Opaque span per row, and the subject's bounds. */
  const ALPHA_MIN = 16;
  const spanMin = new Int32Array(h).fill(-1);
  const spanMax = new Int32Array(h).fill(-1);
  let top = -1, bottom = -1, opaque = 0;
  for (let y = 0; y < h; y++) {
    let lo = -1, hi = -1;
    for (let x = 0; x < w; x++) {
      if (data[(y * w + x) * 4 + 3] < ALPHA_MIN) continue;
      if (lo < 0) lo = x;
      hi = x;
      opaque++;
    }
    spanMin[y] = lo; spanMax[y] = hi;
    if (lo >= 0) { if (top < 0) top = y; bottom = y; }
  }
  if (top < 0) return null;

  /* No transparency at all means this is not a cut-out - an old scan, or a
   * JPEG re-saved as PNG. There is nothing to measure and a guess would be
   * worse than the existing crop, so hand back nothing. */
  if (opaque > w * h * 0.995) return null;

  const width = y => (spanMin[y] < 0 ? 0 : spanMax[y] - spanMin[y] + 1);

  /* A reference width from the top of the head, where nothing else can
   * intrude. Median rather than mean: the very first rows are a few pixels of
   * hair and would drag an average down. */
  const refRows = [];
  const refDepth = Math.max(3, Math.round((bottom - top + 1) * 0.12));
  for (let y = top; y < Math.min(h, top + refDepth); y++) if (width(y)) refRows.push(width(y));
  refRows.sort((a, b) => a - b);
  const crown = refRows[Math.floor(refRows.length / 2)] || 1;

  /* Walk down until the subject is decisively wider than the crown. 1.55 sits
   * between a head at its widest (cheekbones, maybe 1.2x the crown) and
   * shoulders (well past 2x), so it is not near either. */
  const SHOULDER = 1.55;
  let neck = bottom;
  let headW = crown;
  for (let y = top; y <= bottom; y++) {
    const wy = width(y);
    if (!wy) continue;
    if (wy > crown * SHOULDER) { neck = y; break; }
    if (wy > headW) headW = wy;
  }
  const headH = Math.max(4, neck - top);
  /* Horizontal centre from the head rows only: shoulders are often asymmetric
   * and would pull the centre sideways. */
  let cxLo = w, cxHi = -1;
  for (let y = top; y < neck; y++) {
    if (spanMin[y] < 0) continue;
    if (spanMin[y] < cxLo) cxLo = spanMin[y];
    if (spanMax[y] > cxHi) cxHi = spanMax[y];
  }
  const headCx = cxHi < 0 ? w / 2 : (cxLo + cxHi) / 2;

  const scale = (outH * TILE_HEAD_HEIGHT) / headH;
  let cw = Math.round(outW / scale), ch = Math.round(outH / scale);
  cw = Math.max(1, Math.min(cw, w));
  ch = Math.max(1, Math.min(ch, h));

  let x = Math.round(headCx - cw / 2);
  let y = Math.round(top + headH / 2 - ch * TILE_HEAD_CENTRE);
  x = Math.max(0, Math.min(x, w - cw));
  y = Math.max(0, Math.min(y, h - ch));

  const box = png.crop(img, x, y, cw, ch);
  return { buf: png.encodePng(png.resize(box, outW, outH)), method: "head" };
}
