/* Shared headshot resolution for the offline builders.
 *
 * WHY THIS EXISTS
 *
 * nba-headshots ships 1,785 face crops, but its players/metadata/players.json
 * describes only 572 of them — the active roster the pipeline last refreshed.
 * Every builder here trusted that file, so Kareem, Jordan, Kobe, Karl Malone
 * and Tim Duncan all had a committed PNG sitting in the repo and still drew a
 * blank silhouette. Headshot coverage on the bar chart races read 5%.
 *
 * So the file listing is the source of truth for WHICH faces exist, and
 * nba-player-data's player-headshots.json is the only thing that maps a NAME to
 * one of those files.
 *
 * THE TRAP IN THAT MAP
 *
 * It resolves some fathers to their sons' photos:
 *
 *     "Larry Nance"      -> 1626204-larry-nance-jr
 *     "Tim Hardaway"     -> 203501-tim-hardaway-jr
 *     "Jaren Jackson"    -> 1628991-jaren-jackson-jr
 *     "Dee Brown (1968)" -> 200793-dee-brown
 *
 * Using it raw puts the wrong man's face on a card. The guard: a mapped file is
 * accepted only when the slug in the filename matches the slugified player
 * name exactly. That rejects all four cases above.
 *
 * It also rejects ~60 harmless ones where the map simply drops a "Jr." that has
 * no elder counterpart (Danuel House, Dennis Smith, Charlie Brown). Those lose
 * a face they could have had. That is the intended trade: an initials disc is a
 * blemish, the wrong player's face is a lie.
 *
 * players.json stays in the mix as a trusted overlay — it is generated by the
 * pipeline itself, has no collisions, and agrees with every slug-checked entry.
 */

import fs from "fs";
import path from "path";
import zlib from "zlib";

/* ---------------- alpha bounding box ----------------
 *
 * The face crops are cut-outs: RGBA, background removed, and the head occupies
 * only about 46% of the 256px width and 58% of the height. Drawing the whole
 * canvas makes the head tiny; clipping it to a circle to compensate cuts off
 * ears, chin and hair. Neither is acceptable.
 *
 * So the real extent of the head is measured here, at build time, and shipped
 * with the race as a normalized [x, y, w, h] source rectangle. The player draws
 * exactly that region, whole, scaled to fit — nothing cropped, nothing tiny.
 *
 * Done with Node's own zlib rather than an image library on purpose: these
 * builders are run with a bare `node tools/build_races.mjs`, and adding a
 * dependency would mean an npm install before every build.
 *
 * Handles 8-bit non-interlaced truecolour-with-alpha (colour type 6), which is
 * what every file in nba-headshots is. Anything else returns null and the
 * caller falls back to the full canvas.
 */
function alphaBox(file) {
  let buf;
  try { buf = fs.readFileSync(file); } catch (e) { return null; }
  if (buf.length < 8 || buf.readUInt32BE(0) !== 0x89504e47) return null;

  let w = 0, h = 0, depth = 0, colour = 0, interlace = 0;
  const idat = [];
  let off = 8;
  while (off + 8 <= buf.length) {
    const len = buf.readUInt32BE(off);
    const type = buf.toString("ascii", off + 4, off + 8);
    const data = buf.subarray(off + 8, off + 8 + len);
    if (type === "IHDR") {
      w = data.readUInt32BE(0); h = data.readUInt32BE(4);
      depth = data[8]; colour = data[9]; interlace = data[12];
    } else if (type === "IDAT") {
      idat.push(data);
    } else if (type === "IEND") break;
    off += 12 + len;
  }
  if (depth !== 8 || colour !== 6 || interlace !== 0 || !w || !h) return null;

  let raw;
  try { raw = zlib.inflateSync(Buffer.concat(idat)); } catch (e) { return null; }

  const bpp = 4, stride = w * bpp;
  if (raw.length < (stride + 1) * h) return null;

  // Un-filter in place. Each scanline is one filter byte then `stride` bytes.
  const cur = Buffer.alloc(stride);
  const prev = Buffer.alloc(stride);
  let minX = w, minY = h, maxX = -1, maxY = -1;
  const ALPHA_MIN = 16;   // ignore the soft feathered edge the cut-out leaves

  for (let y = 0; y < h; y++) {
    const base = y * (stride + 1);
    const filter = raw[base];
    raw.copy(cur, 0, base + 1, base + 1 + stride);
    for (let i = 0; i < stride; i++) {
      const a = i >= bpp ? cur[i - bpp] : 0;   // left
      const b = prev[i];                       // up
      const c = i >= bpp ? prev[i - bpp] : 0;  // up-left
      let v = cur[i];
      if (filter === 1) v += a;
      else if (filter === 2) v += b;
      else if (filter === 3) v += (a + b) >> 1;
      else if (filter === 4) {
        const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
        v += (pa <= pb && pa <= pc) ? a : (pb <= pc ? b : c);
      }
      cur[i] = v & 0xff;
    }
    for (let x = 0; x < w; x++) {
      if (cur[x * bpp + 3] >= ALPHA_MIN) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
    cur.copy(prev);
  }
  if (maxX < 0) return null;
  const r = n => Math.round(n * 1000) / 1000;
  return [r(minX / w), r(minY / h), r((maxX - minX + 1) / w), r((maxY - minY + 1) / h)];
}

export const HEADSHOT_BASE =
  "https://jsierrahoopshype.github.io/nba-headshots/players/headshots/face/";
export const SILHOUETTE =
  "https://jsierrahoopshype.github.io/nba-headshots/fallbacks/player_silhouette.svg";

function slugify(name) {
  return String(name)
    .toLowerCase()
    .replace(/['.&]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/* Accepts either the repo root or the players/metadata directory, so existing
 * command lines keep working. Returns the directory holding the face crops, or
 * null when it cannot be found. */
function findFaceDir(hsPath) {
  const candidates = [
    path.join(hsPath, "players", "headshots", "face"),           // repo root
    path.join(hsPath, "..", "headshots", "face"),                 // players/metadata
    path.join(hsPath, "headshots", "face"),                       // players/
    path.join(hsPath, "face")
  ];
  for (const c of candidates) {
    try { if (fs.statSync(c).isDirectory()) return c; } catch (e) { /* next */ }
  }
  return null;
}

/**
 * @param {string} hsPath  nba-headshots repo root or its players/metadata dir
 * @param {object} headMap nba-player-data/player-headshots.json (name -> slug)
 * @returns {{ urlFor:(name:string)=>string|null, faceOf:(name:string)=>string,
 *             size:number, stats:object }}
 */
export function buildFaceIndex(hsPath, headMap) {
  const stats = { onDisk: 0, fromMetadata: 0, fromMap: 0, rejected: 0, rejects: [] };

  const faceDir = findFaceDir(hsPath);
  const onDisk = new Set();
  if (faceDir) {
    for (const f of fs.readdirSync(faceDir)) {
      if (/\.png$/i.test(f)) onDisk.add(f.replace(/\.png$/i, ""));
    }
  }
  stats.onDisk = onDisk.size;

  const byName = new Map();

  // 1. the pipeline's own metadata, where it exists
  let meta = null;
  for (const p of [path.join(hsPath, "players.json"),
                   path.join(hsPath, "players", "metadata", "players.json")]) {
    try { meta = JSON.parse(fs.readFileSync(p, "utf8")); break; } catch (e) { /* next */ }
  }
  for (const p of ((meta && meta.players) || [])) {
    const h = p.headshot;
    if (!h || !h.face || !h.filename) continue;
    const slug = h.filename.replace(/\.png$/i, "");
    if (onDisk.size && !onDisk.has(slug)) continue;   // metadata ahead of the files
    byName.set(p.full_name, slug);
    stats.fromMetadata++;
  }

  // 2. the name map, gated on the file existing AND the slug matching the name
  if (onDisk.size) {
    for (const [name, slug] of Object.entries(headMap || {})) {
      if (!slug || byName.has(name) || !onDisk.has(slug)) continue;
      const tail = slug.indexOf("-") >= 0 ? slug.slice(slug.indexOf("-") + 1) : "";
      if (tail === slugify(name)) {
        byName.set(name, slug);
        stats.fromMap++;
      } else {
        stats.rejected++;
        if (stats.rejects.length < 6) stats.rejects.push(`${name} -> ${slug}`);
      }
    }
  }

  // Cached because several races share the same players and each box costs a
  // full PNG inflate.
  const boxCache = new Map();
  function boxFor(name) {
    if (!faceDir || !byName.has(name)) return null;
    const slug = byName.get(name);
    if (!boxCache.has(slug)) boxCache.set(slug, alphaBox(path.join(faceDir, slug + ".png")));
    return boxCache.get(slug);
  }

  return {
    size: byName.size,
    stats,
    urlFor: name => (byName.has(name) ? HEADSHOT_BASE + byName.get(name) + ".png" : null),
    faceOf: name => (byName.has(name) ? HEADSHOT_BASE + byName.get(name) + ".png" : SILHOUETTE),
    /* Normalized [x, y, w, h] of the head inside its 256x256 canvas, so a
     * renderer can draw the whole head at a sensible size. null = draw it all. */
    boxFor
  };
}

export function reportFaceIndex(idx, label) {
  const s = idx.stats;
  if (!s.onDisk) {
    console.log(`${label}: ${idx.size} faces from metadata only — the face directory was ` +
      `not found next to the path given, so coverage is limited to the active roster. ` +
      `Pass the nba-headshots repo root to use all of them.`);
    return;
  }
  console.log(`${label}: ${idx.size} names resolved to a face ` +
    `(${s.fromMetadata} from players.json, ${s.fromMap} more from the verified name map; ` +
    `${s.onDisk} PNGs on disk, ${s.rejected} mappings rejected as name/slug mismatches).`);
  if (s.rejects.length) console.log(`  rejected e.g. ${s.rejects.join(", ")}`);
}
